# Menus
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  About: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: https://avatars2.githubusercontent.com/u/13016470?v=3&s=400
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: 吴晓然
        author_title: Web 前端 & NodeJs
        location: 天朝，帝都
        follow: https://github.com/wxrbwran/
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: https://github.com/wxrbwran/
        #twitter: /
        #facebook: /
        #dribbble: /
       # rss: /
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: omSPY4JPADoaY_EZ5Y16 # enter swiftype install key here
    # baidu: true # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    # disqus: hexo-theme-icarus # enter disqus shortname here
    duoshuo: xiaoranhexo
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justified-gallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
